name: mobile
description: "Fitness App - mobile client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management & DI
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Network
  dio: ^5.7.0

  # Local storage
  shared_preferences: ^2.3.4

  # Device info
  device_info_plus: ^11.2.0

  # Code generation annotations
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Testing
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0

  # Code generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
